service: on-call-bot-serverless
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
functions:
  slack:
    handler: dist/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
#  - serverless-localstack
  - serverless-webpack
package:
  excludeDevDependencies: true
#  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  localstack:
    debug: true
    autostart: true
    stages:
      # list of stages for which the plugin should be enabled
      - dev
      - local
  lambda:
    mountCode: true
